// <auto-generated />
using System;
using Chunya5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chunya5.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220220073020_modifyTradeProp")]
    partial class modifyTradeProp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Chunya5.Models.Bonds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddMan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BondsCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BondsName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModifyMan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ParValue")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("Rate")
                        .HasColumnType("double");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Bonds");
                });

            modelBuilder.Entity("Chunya5.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AccInterest")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("AccUninterestImcome")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Accout")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddMan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("BondsCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("DenominattonHeld")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("FloatingPl")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("InterestCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsDeleteete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifyMan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("NetCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("RealizedInterestIncome")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalInterestIncome")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TradingProloss")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Chunya5.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Accrued")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AddMan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("BondsCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Deno")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ModifyMan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("NetPrace")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Trade");
                });
#pragma warning restore 612, 618
        }
    }
}
